on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run test cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/checkout@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run test cases
        run: npm jest
