on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run testcases
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/srv-movies

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/checkout@v2

        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run testcases
        run: npm jest
